image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

stages:
  - test
  - deploy

.test:
  stage: test
  parallel:
    matrix:
      - TAG:
        - "nightly"
        - "4.0-acadia-stable"
        - "4.0-canyonlands-stable"
  image: eicweb.phy.anl.gov:4567/containers/eic_container/jug_xl:${TAG}

run_hepmc3_local:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc EVGEN/CI/
    - COPYRECO=true scripts/run.sh EVGEN/CI/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc 20
    - test -f RECO/*/CI/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.root

run_hepmc3_local_0001:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc EVGEN/CI/
    - COPYRECO=true scripts/run.sh EVGEN/CI/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc 20 1
    - test -f RECO/*/CI/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.0001.root

run_hepmc3_s3:
  extends: .test
  script:
    - COPYRECO=true scripts/run.sh EVGEN/TEST/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc 20
    - test -f RECO/*/TEST/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.root

run_hepmc3_s3_0001:
  extends: .test
  script:
    - COPYRECO=true scripts/run.sh EVGEN/TEST/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc 20 1
    - test -f RECO/*/TEST/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.0001.root

run_hepmc3_s3_gz:
  extends: .test
  script:
    - COPYRECO=true scripts/run.sh EVGEN/TEST/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc.gz 20
    - test -f RECO/*/TEST/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.root

run_hepmc3_s3_gz_0001:
  extends: .test
  script:
    - COPYRECO=true scripts/run.sh EVGEN/TEST/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc.gz 20 1
    - test -f RECO/*/TEST/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.0001.root

jug_xl:master:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_SERVER_HOST == "eicweb.phy.anl.gov"'
      when: on_success
    - when: never
  needs:
    - run_hepmc3_local
    - run_hepmc3_local_0001
    - run_hepmc3_s3
    - run_hepmc3_s3_0001
  trigger:
    project: containers/eic_container
  allow_failure: true
