image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

stages:
  - test

.test:
  stage: test
  parallel:
    matrix:
      - TAG:
        - "nightly"
  image: eicweb.phy.anl.gov:4567/containers/eic_container/jug_xl:${TAG}

run_hepmc3_local_hepmc:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc EVGEN/CI/
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc 20
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.eicrecon.tree.edm4eic.root

run_hepmc3_local_hepmc_0001:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc EVGEN/CI/
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc 20 0000
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.0000.eicrecon.tree.edm4eic.root

run_hepmc3_local:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc EVGEN/CI/
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc 20
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.eicrecon.tree.edm4eic.root

run_hepmc3_local_hepmc3:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3 20
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.eicrecon.tree.edm4eic.root

run_hepmc3_local_hepmc3_gz:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3
    - gzip EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3.gz 20
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.eicrecon.tree.edm4eic.root

run_hepmc3_root_local:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3.tree.root EVGEN/CI/
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3.tree.root 20
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.eicrecon.tree.edm4eic.root

run_hepmc3_root_local_0001:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3.tree.root EVGEN/CI/
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3.tree.root 20 0000
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.0000.eicrecon.tree.edm4eic.root

run_hepmc3_root_remote:
  extends: .test
  script:
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3.tree.root 20
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.eicrecon.tree.edm4eic.root

run_hepmc3_root_remote_0001:
  extends: .test
  script:
    - COPYRECO=true scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc3.tree.root 20 0000
    - ls -al RECO/*/*/CI/
    - test -f RECO/*/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.0000.eicrecon.tree.edm4eic.root
