image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

run_hepmc3:
  stage: test
  script:
    - scripts/run.sh EVGEN/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc 20

run_hepmc3_0001:
  stage: test
  script:
    - scripts/run.sh EVGEN/DIS_NC_Q2gt10_crossDivNrgCrab_25mRad_5x41_v2_20ev.hepmc 20 1
