image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

stages:
  - test

.test:
  stage: test
  parallel:
    matrix:
      - TAG:
        - "nightly"
  image: eicweb.phy.anl.gov:4567/containers/eic_container/jug_xl:${TAG}

run_hepmc3_local:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc EVGEN/CI/
    - COPYRECO=true RECONSTRUCTION=*.py scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc 20
    - ls -al RECO/*/CI/
    - test -f RECO/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.root

run_hepmc3_local_0001:
  extends: .test
  script:
    - mkdir -p EVGEN/CI/ && cp -f test/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc EVGEN/CI/
    - COPYRECO=true RECONSTRUCTION=*.py scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc 20 1
    - ls -al RECO/*/CI/
    - test -f RECO/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.0001.root

run_hepmc3_s3:
  extends: .test
  script:
    - COPYRECO=true RECONSTRUCTION=*.py scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc 20
    - ls -al RECO/*/CI/
    - test -f RECO/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.root

run_hepmc3_s3_0001:
  extends: .test
  script:
    - COPYRECO=true RECONSTRUCTION=*.py scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc 20 1
    - ls -al RECO/*/CI/
    - test -f RECO/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.0001.root

run_hepmc3_s3_gz:
  extends: .test
  script:
    - COPYRECO=true RECONSTRUCTION=*.py scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc.gz 20
    - ls -al RECO/*/CI/
    - test -f RECO/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.root

run_hepmc3_s3_gz_0001:
  extends: .test
  script:
    - COPYRECO=true RECONSTRUCTION=*.py scripts/run.sh EVGEN/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.hepmc.gz 20 1
    - ls -al RECO/*/CI/
    - test -f RECO/*/CI/pythia8NCDIS_5x41_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1_20ev.0001.root
